name: SAST Comparison

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/SAST.yml

jobs:
  semgrep-free:
    name: Semgrep Free Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Semgrep scan
      - name: Run Semgrep scan
        run: |
          semgrep scan --json --json-output /tmp/semgrep.json

      # Step 3: View the Semgrep output in logs
      - name: View the output
        run: cat /tmp/semgrep.json

      # Step 4: Upload the Semgrep output as an artifact
      - name: Upload Semgrep output
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-output
          path: /tmp/semgrep.json
